[tool.poetry]
name = "nosok-bot"
version = "0.1.0"
description = "Discord music bot"
authors = ["l4blee <76159455+l4blee@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "3.10" 
"discord.py" = "^1.7.3"
peewee = "^3.14.8"
youtube_dl = "^2021.6.6"
PyNaCl = "^1.4.0"
soundcloud-v2 = "^1.1.6"
python-dotenv = "^0.19.2"
discord-components = "^2.1.2"
psutil = "^5.8.0"
psycopg2 = "^2.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
